# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-02 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('mobilenum', models.IntegerField(max_length=100)),
                ('emailId', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
