# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-02 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20180926_1124'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurencyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curency', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('currencyValue', models.CharField(max_length=200)),
                ('curobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.TrainCurrencies')),
            ],
        ),
    ]
