# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-24 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_curencycheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='mobilenum',
            field=models.IntegerField(),
        ),
    ]
