# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencuValue', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
                ('imagesCurrency', models.FileField(upload_to='train/')),
            ],
        ),
    ]
